name: Sync Fork

on:
  schedule:
  - cron:  "0 0 * * *"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2.0.0
      with:
        source_repo: "vdurmont/emoji-java"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
